### ISSUE TITLE
Unable to resolve path to module w/ eslint: import/no-unresolved

### ISSUE THREAD

**Issue by gregveres** [frenic/csstype#113]
We recently changed our eslint rules to include import/no-unresolved
Now I get an error on 
import * as CSS from 'csstype';

I get unable to resolve path to module. 

I have seen the other issues where the solution is to ensure that tsconfig.ts: compilerOptions.moduleResolution = 'node' and that is what mine is set to.

Any suggestions?

**Comment by frenic** [comment]
I'm not sure. Never heard of this before. Maybe because Typescript provides similar errors. But I think this issue should be raised at ESLint.

**Comment by gregveres** [comment]
You are probably right. 
BTW, I converted the index.d.ts into a standard ts file and things work better. I had to rearrange things because you output things in alphabetical order rather than in use order, but after that everything works great.

**Comment by djmisterjon** [comment]
get same issue , i try many way ! 
Any tips ? 
![image](https://user-images.githubusercontent.com/24865815/93957829-14a10100-fd23-11ea-8ac3-daee6f0f7ef4.png)

**Comment by frenic** [comment]
@djmisterjon That seems to be a type error thought?

**Comment by djmisterjon** [comment]
i found a workaround with import directly in jsdoc.

but i'm a bit idiot 🥇 , i just found out that React already has all types for css with CSSProperties['key'] !
So those thing work both, sorry for the inconvenience.
```js
	* @param {import('csstype').Property.FlexDirection} [props.FlexDirection] - Using Import() with csstype
	* @param {React.CSSProperties['flexDirection']} [props.FlexDirection] - Using arrayKey with React
```
all fine thanks

**Comment by paztis** [comment]
the problem is the field "main" in the package.json is empty
eslint-plugin-import tries to resolve the main field and fails.
 
You need to provide a index.js file, even if this one is empty.
IN fact you need to provide the index.d.ts and the index.js produced by the typescript compilation
