### ISSUE TITLE
FontWeight doesn't accept absolute values passed as strings

### ISSUE THREAD

**Issue by villasv** [frenic/csstype#125]
I'm getting `Type '"100"' is not assignable to type 'FontWeight | undefined'.` when using a library that specifies a few CSS constants and declares it's types as possibly stringified numerals.

**Comment by frenic** [comment]
Union string (`... | string`) is needed to make this work today and is avoided whenever possible. To solve this we first need to implement a TS4.1 alternative and use `` number | `${number}` `` to make `100` and `"100"` work, but not e.g. `"lihgter"`.

**Comment by villasv** [comment]
Any pointer for me to go about it? I think I have the time to contribute, but I couldn't figure out how to based on recent pull requests.

**Comment by frenic** [comment]
That would be helpful! [This guy](https://github.com/frenic/csstype/blob/923ae487a92ddd2aeb3adf5a5724ebd485579e52/src/typescript.ts#L133-L158) converts CSSType-"types" into understandable TypeScript types. The string template literal needs to be opt-in here somewhere so we can generate a d.ts with string template literals and one without later on.

**Comment by itlgit** [comment]
The other scenario is using a CSS var for fontWeight (and any other property). This reports an error from csstypes:
`fontWeight: 'var(--custom-font-weight)'`

**Comment by frenic** [comment]
Untion string is now also applied wherever union number is applied. Released in 3.0.10. I need more time to solve this separately with template string for TS4.1+.
