### ISSUE TITLE
DevDependencies?

### ISSUE THREAD

**Issue by Vadorequest** [frenic/csstype#129]
Shouldn't this package be installed as a devDependency, instead of a dependency?

If so, the readme should be updated.

**Comment by frenic** [comment]
No, it should be installed as a dependency. This package includes types only so it doesn't result in any bundled code anyway.

**Comment by Vadorequest** [comment]
Yeah, it was confusing me. But it's true the types are required when building, not only when working on a local environment, and if types are missing they would break the build. It makes more sense now, thanks.
