### ISSUE TITLE
BoxShadow does not support TLength generic

### ISSUE THREAD

**Issue by wintercounter** [frenic/csstype#135]
In many CSS-in-JS solutions the following declaration of `box-shadow` is allowed:

```
boxShadow: [5, 5, 10, '#000']
```

For example we're using custom generics to support such values. However `CSS.Property.BoxShadow` does not come with support for generics, so it'll ignore the passed `TLength` type property.

**Comment by frenic** [comment]
CSSType should be as close to the correct CSS-specification as possible. `box-shadow` are handled differently in different CSS-in-JS libraries and this issue should be addressed there, not here.

**Comment by wintercounter** [comment]
But it cannot be handled at library level. With extending CSSType I'll lose all that IntelliSense has to offer, unless I copy my own DocBlock. For border, margin, padding, background, etc. this work fine. I don't see why box-shadow needs to be different.

Anyway, thanks for checking, we will figure out something then on our own.

**Comment by frenic** [comment]
Can you provide an example of how you extend e.g. `padding` to give me a better understanding of your problem?

**Comment by wintercounter** [comment]
```
type ValueTypes =
    | string
    | number
    | boolean
    | (string | number | boolean)[]

interface Props extends CSS.PropertiesFallback<ValueTypes> {
   ...
}
```

This allows to do such for example: `padding: [1, 2, 'auto', 4]`. That's because `padding` supports `TLength` (which is the passed `ValueTypes` generic). But `boxShadow` doesn't, doing `boxShadow: [1, 2, 3, '#000']` will throw TS error.

**Comment by frenic** [comment]
Ok, I understand. But for this to work out of the box, we'll need to put `TLength` on `boxShadow` and that isn't valid CSS. You can't do `box-shadow: 10px`. So that won't happen. But maybe something like this would help you?

```ts
type ValueTypes = string | number | boolean | (string | number | boolean)[];

type CustomProperties = {
  boxShadow: CSS.Property.BoxShadow | ValueTypes;
};

interface Props extends Omit<CSS.PropertiesFallback<ValueTypes>, keyof CustomProperties>, CustomProperties {}

const style: Props = {
  boxShadow: [1, 2, 3, '#000'], // OK 👌
};
```

**Comment by wintercounter** [comment]
Unfortunately with that I'm still losing the docs of the property, since I'm completely overriding it.

![image](https://user-images.githubusercontent.com/963776/133881263-fd0b2360-3da2-4b40-8fbc-08d6551b71cb.png)
![image](https://user-images.githubusercontent.com/963776/133881291-dc49177b-e838-43f4-b970-2cdccbbb540b.png)

**Comment by frenic** [comment]
This would solve that:

```ts
type ValueTypes = string | number | boolean | (string | number | boolean)[];

type CustomProperyNames = 'boxShadow';

type CustomProperties = {
  [property in keyof Pick<CSS.PropertiesFallback, CustomProperyNames>]: CSS.PropertiesFallback[property] | ValueTypes;
};

interface Props extends Omit<CSS.PropertiesFallback<ValueTypes>, keyof CustomProperties>, CustomProperties {}

const style: Props = {
  boxShadow: [1, 2, 3, '#000'], // OK 👌
};

**Comment by wintercounter** [comment]
Thanks, it does work. This is a fun workaround. Can I tip you somehow? :)

**Comment by frenic** [comment]
Thanks for offering a donation but this one's on me 🙂 Happy it worked!
