### ISSUE TITLE
How to add "!important" on zIndex?

### ISSUE THREAD

**Issue by khandar-william** [frenic/csstype#142]
Hi, one of our library dependency uses csstype to provide typings.
On the field `zIndex` I notice you decide to use 
```
export type Globals = "-moz-initial" | "inherit" | "initial" | "revert" | "unset";
export type ZIndex = Globals | "auto" | (number & {});
```

but what if I need to set `zIndex: '100 !important'`? 
currently I got a typing error and I must forcefully ignore it with `zIndex: ('100 !important') as any`

is there a better way to use `!important` with zIndex?

**Comment by frenic** [comment]
In v3.0.10 union `string` is applied to all properties that has `number` so this should be resolved without the need to asset the value.
