### ISSUE TITLE
Error: Property 'height' does not exist on type 'CSSProperties'

### ISSUE THREAD

**Issue by KutnerUri** [frenic/csstype#156]
Getting this very weird error when trying to read `height` property:

> Error: Property 'height' does not exist on type 'CSSProperties'

For example:
```
const props: CSSProperties = {
  height: 3, // totally fine
};

const a = props.height; // ts error
```

any ideas?

using version `^3.0.2`, coming from `types/react`: `18.0.7`

**Comment by maurer2** [comment]
Hello, v3 changed the way Properties are exposed ([CSSProperties](https://github.com/frenic/csstype#version-30)). The following should work:

```js
import type * as CSS from 'csstype';

const props: CSS.Properties = {
  height: '3px',
};

const a = props.height;
```

Cheers

**Comment by frenic** [comment]
I guess it's `React.CSSProperties` in your example. I don't get any errors at my end so I'm not able to assist you.

![image](https://user-images.githubusercontent.com/237182/171363587-5196cd78-874f-4d13-b6b7-553a42403c2e.png)
