### ISSUE TITLE
Issue with Vite 3: Failed to resolve entry for package "csstype"

### ISSUE THREAD

**Issue by DavidVaness** [frenic/csstype#162]
Hi, I am getting the following error using this library with vite 3

```
[plugin: vite:dep-scan] Failed to resolve entry for package "csstype". The package may have incorrect main/module/exports specified in its package.json.
```

i tried to fix this locally by patching the the "main": "" out of the package.json but without any luck of resolving this issue.
Maybe I am misunderstanding the error message 🤔 

usage in code is everywhere like this
`import * as CSS from 'csstype'`

**Comment by meyer** [comment]
duplicate of #158. try changing `import *` to `import type *`. Context here: https://github.com/frenic/csstype/issues/158#issuecomment-1125157572

**Comment by DavidVaness** [comment]
This is it! Thank you
