### ISSUE TITLE
Hyphen-separated property names

### ISSUE THREAD

**Issue by pelotom** [frenic/csstype#2]
Hi, this project looks awesome! I’m trying to improve the [typings for JSS](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23116) and these typings look very promising in that effort. However, there’s a need in that library for both camel cased and hyphen-separated CSS property names. Would it be possible to generate a kebab-cased version of the `Properties` interface?

**Comment by frenic** [comment]
Sure, I agree. There should be a hyphened version. I'll look into it as soon as I can. Should be quite easy.

**Comment by frenic** [comment]
However, autocompletion of properties with both of them will become quite bloated. It will be like this for each property:

```
color
Color
...
display
Display
```

You should maybe choose one casing as default and let your users extend using module argumentation with the other casing if it's needed for them.

**Comment by frenic** [comment]
It seems like VSCode groups the ones that needs quotes separately so maybe it won't be an issue.

![image](https://user-images.githubusercontent.com/237182/35768180-1c43e20a-08f8-11e8-8d89-0cf81de64c6c.png)

**Comment by pelotom** [comment]
Sorry, to be clear: I think they should be separate interfaces. I’m guessing most CSS-in-JS libs don’t need the kebab-case version, so it shouldn’t be part of the interface they use.

**Comment by frenic** [comment]
Yeah, that's what I though too.

**Comment by frenic** [comment]
Fixed in v1.5.0
