### ISSUE TITLE
page-break-(after|before) missing 'recto' and 'verso' as possible values

### ISSUE THREAD

**Issue by pelotom** [frenic/csstype#29]
https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-after
https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-before

**Comment by frenic** [comment]
Added PR, https://github.com/mdn/data/pull/203

**Comment by frenic** [comment]
Fixed in f318f12480734ff97c82b9b614a0c58a24e1863b
