### ISSUE TITLE
Finally someone did this!

### ISSUE THREAD

**Issue by kof** [frenic/csstype#3]
I created this placeholder repo https://github.com/cssinjs/style-type-generator and was looking for someone who can take this task. I could't do it, having myself too much to maintain! 

Looking forward to make this ts typings work with JSS  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23116

As well as making it work with flow!

Also JSS syntax has a number of syntactic sugar extensions, which will cause some more work. If you can help with this, please do!

**Comment by frenic** [comment]
You can have a peek in https://github.com/frenic/glitz/blob/master/packages/type/index.d.ts for some inspiration. 

It should definitely compile onto an equivalent Flow  type as well. I'm not too familiar with Flow though. But it shouldn't be too hard to manage.

**Comment by meyer** [comment]
@frenic This is rad, thanks! I was working on an MDN CSS syntax parser a while ago but got very distracted by other projects.

I’d like to use it with [jsxstyle](https://github.com/smyte/jsxstyle). Will probably have some questions/issues for you in the near future.

**Comment by frenic** [comment]
It would an honor to help out. Currently working on an equivalent flow type as well.

**Comment by frenic** [comment]
Flow types added in v1.6.0
