### ISSUE TITLE
text-align missing 'justify-all' as a possible value

### ISSUE THREAD

**Issue by pelotom** [frenic/csstype#30]
https://developer.mozilla.org/en-US/docs/Web/CSS/text-align

**Comment by frenic** [comment]
No browsers supports it. Not sure why but lets see what they say. https://github.com/mdn/data/pull/204

Thanks a lot ❤️

**Comment by frenic** [comment]
Won't be fixes at the moment, see https://github.com/mdn/data/pull/204
