### ISSUE TITLE
background-clip missing possible 'text' value

### ISSUE THREAD

**Issue by pelotom** [frenic/csstype#31]
https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip

**Comment by frenic** [comment]
The `border` keyword seems to be missing too, https://github.com/mdn/data/pull/201

**Comment by frenic** [comment]
The spec tells us it's not ready for implementation. Closing for now.

https://drafts.csswg.org/css-backgrounds-4/#background-clip
