### ISSUE TITLE
overflow-anchor and -webkit-line-clamp

### ISSUE THREAD

**Issue by xaviergonz** [frenic/csstype#34]
Since very recently uses this package for CSS properties, but the following are now missing that didn't use to be missing before using this package:

overflowAnchor (overflow-anchor) https://css-tricks.com/almanac/properties/o/overflow-anchor/
WebkitLineClamp (-webkit-line-clamp)

also react had a fallback for [key: string]: any, but I guess that's up to them to add it back?

**Comment by frenic** [comment]
The index signature was removed to provide closed typing. [I created a pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24939/files) where I add a comment how to solve these sort of things using module augmentation.

`overflow-anchor` seems to be missing in MDN data and should definitely be added.

**Comment by xaviergonz** [comment]
as for -webkit-line-clamp https://css-tricks.com/line-clampin/

**Comment by pelotom** [comment]
The easiest thing for when there are missing properties like this is probably just a simple cast:

```ts
<div style={{ ['overflowAnchor' as any]: 'auto' }}>
  ...
</div>
```

That said, using module augmentation has the benefit of being more type safe (in the case where you use the property in more than one place) and also gathers together in one place all the temporary patches you're having to make to the base CSSType `Properties`, so they can easily be removed again once CSSType acquires them.

**Comment by xaviergonz** [comment]
I didn't know that was even possible, nice trick :D

**Comment by frenic** [comment]
Added that example with assertion and module augmentation to the README [here](https://github.com/frenic/csstype#what-should-i-to-do-when-i-get-type-errors).

**Comment by frenic** [comment]
Solved by https://github.com/mdn/data/pull/206 and c817c8593b8f18a7fb6283a98eb6847cf4f4f2fd
