### ISSUE TITLE
Missing description on the GitHub repo

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [frenic/csstype#5]
![image](https://user-images.githubusercontent.com/3335181/35877475-37422948-0b2a-11e8-8773-88f48b5ea012.png)

I'm probably going to introduce this to a project or two once issues 2 & 4 are resolved... would be nice to not have missing fields. ;)

**Comment by frenic** [comment]
Oh gosh, thanks. I didn't prioritized those things when I started this as an experimental project. I'm currently working on some structural details with the generator to be able to add more features and better types. #2 & #4 will be next.

**Comment by JoshuaKGoldberg** [comment]
Awesome, thanks :)
