### ISSUE TITLE
Change license to MPL

### ISSUE THREAD

**Issue by frenic** [frenic/csstype#50]
It occurs that any new files containing MPL covered data (like MDN data) must also be distributed under MPL ([see discussion](https://github.com/mdn/data/issues/210#issuecomment-387572808)). 

Our options:

1. Change from MIT to MPL
2. Generate typings as a install script with MDN data as a dependency to keep the MIT license

Option 1 seems preferable. But I don't know what impact that would have and don't know how a process like that works.

cc @chrisdavidmills @pelotom

**Comment by chrisdavidmills** [comment]
Yup, you've got that right. And anything you've written that sits alongside the MPL-licensed files or data does not have to be under MPL - it can be under any license you like.

I am not sure if you need to do anything here. It is OK to have two licenses governing one codebase. But you might want to keep your codebase pure (one license) and all under something more permissive like MIT.

**Comment by frenic** [comment]
The typings (_index.d.ts and index.js.flow_) exists in the codebase to easily diff the results of the generator. That's quite handy for reviewing and I can't figure out a simple alternative way of doing this.

The summaries needs to be cached otherwise it will spam the MDN site and cause a major impact on build performance.

I'm not dealing with licensing very often so I need to think about how to proceed. If someone has any ideas I would be happy to hear about it.

**Comment by frenic** [comment]
I guess this isn't an issue anymore since mdn-data changed their license to MIT

**Comment by srghma** [comment]
> mdn-data changed their license to MIT

rn lib is Creative Commons Zero v1.0 Universal - https://github.com/mdn/data/blob/main/LICENSE
