### ISSUE TITLE
Type-checking performance

### ISSUE THREAD

**Issue by meyer** [frenic/csstype#51]
I’ve been working on improving our TypeScript check time at work this week. Over the past month our check time has gone from around 15 seconds to almost two minutes (!!!). The major slowdown happened to coincide with me updating jsxstyle—the CSS in JS library I maintain—to use csstype.

The main issue I encountered was not related to csstype. I was intersecting the `Properties` interface with `{ [key: string]: any }` instead of extending it. Big mistake. After I replaced the intersection with an `extends`, check time dropped down to about one minute.

I ran `tsc` with the diagnostics flag and got the following check times:

CSS types |  Check time
:--- | :---
`{ [key: string]: any }` | 22 seconds
Old `CSSProperties` from [@types/react](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9bcf9ea/types/react/index.d.ts#L925) | 32 seconds
`Properties<string \| number>` | 56 seconds

I started messing with a few things to see if I could improve that number.  Inlining `TLength` in `Properties` drops check time to **47 seconds**. I’m currently looking at inlining other things (unexported types that are only used once or twice). My general feeling right now is that a single interface with everything inlined is going to be the fastest option. It’ll be super verbose and lots of things will be duplicated, but since it’s all codegen’d that doesn’t seem like a big issue to me. TypeScript seems to deal better with large type definition files that it does with smaller files that dynamically generate lots of types.

I feel like it should be possible to get check times fairly close to the old check time (pre-csstype). My main issue right now is that I haven’t figured out a good way to profile TypeScript type checking. Seems like a bit of a black box.

I’m still looking into other ways of speeding things up. Will update this issue when I find something interesting.

**Comment by frenic** [comment]
Is that project you're testing on public? 

Does the JSDocs have any affect on `tsc`? You could try v2.3.1 that doesn't have JSDocs. It shouldn't have any affect. But just to make sure.

Thank you for looking into this. I would be happy to hear more.

**Comment by meyer** [comment]
@frenic Brief followup here: this issue has completely gone away and type-checking time is down to around 4 seconds (!!!) with TS 3.1.

**Comment by frenic** [comment]
Nice to hear 👍
