### ISSUE TITLE
[Help wanted] How to apply csstype on an interface

### ISSUE THREAD

**Issue by stephenkoo** [frenic/csstype#53]
I have an object that must only contain specific css properties:
```tsx
export interface InterfaceTypeElementProperties {
  fontFamily?: string;
  fontSize?: [string, number];
  fontWeight?: number;
  letterSpacing?: number;
  textTransform?: string;
  lineHeight?: number | number[];
  marginTop?: number | number[];
  marginBottom?: number | number[];
}
```

I'm hoping to apply csstypes on top of those properties - for instance `fontWeight` shouldn't just accept any number, but those recognised by `csstype`.

What's the right way to do this?
Thank you!

**Comment by frenic** [comment]
I would prefer using the `Pick` type utility in every way I can. However, there's an issue about [loosing the JSDoc](https://github.com/Microsoft/TypeScript/issues/21489) for each property by using mapped types. So it isn't perfect. But hopefully that will be fixed soon enough.

```ts
import * as CSS from "csstype";
type InterfaceTypeElementProperties = Pick<CSS.Properties, "fontFamily" | "fontSize" | "fontWeight" | "letterSpacing" | "textTransform" | "lineHeight" | "marginTop" | "marginBottom">;
```

You can also explicitly use the type value if you don't care about the JSDoc at all.

```ts
export interface InterfaceTypeElementProperties {
  // ...
  fontWeight?: CSS.Properties['fontWeight'];
  // ...
}
```

**Comment by frenic** [comment]
I don't know if I understood you correctly. But if you want to extend `InterfaceTypeElementProperties` your only option is to explicitly use the type value otherwise TS will complain that they don't match.

```ts
export interface InterfaceTypeElementProperties {
  // ...
  fontWeight?: number | CSS.Properties['fontWeight'];
  // ...
}
```

**Comment by stephenkoo** [comment]
I'm still learning TypeScript so I wasn't aware `Pick` existed, thank you.

I think
```tsx
export interface InterfaceTypeElementProperties {
  // ...
  fontWeight?: CSS.Properties['fontWeight'];
  // ...
}
```
gives me the intended effect, thank you.

Just out of curiosity, is there a better way to write this using a combination of `Pick` (to select the desired properties) and `Partial` (to make the selected properties optional)?

**Comment by stephenkoo** [comment]
@frenic Ah, so a more important potential bug - `csstype` doesn't seem to like if you assign 
```tsx
interface InterfaceTest {
  fontWeight?: CSS.Properties['fontWeight'];
}

const anObject = {
  a: 100,
}
const fontWeightA: InterfaceTest = {
  fontWeight: anObject.a,
};
```

Producing errror: `Type 'number' is not assignable to type '100 | 300 | 400 | 500 | 700 | 900 | "-moz-initial" | "inherit" | "initial" | "revert" | "unset" |...'.`

**Comment by stephenkoo** [comment]
My bad, I should define a type to `anObject`:
```
interface InterfaceAnObject = {
  a: CSS.Properties['fontWeight'],
}
```

**Comment by frenic** [comment]
You don't need `Partial` because all properties are already optional in `CSS.Properties`.

**Comment by stephenkoo** [comment]
Ah perfect. Thanks!
