### ISSUE TITLE
Missing css property: WebkitFontSmoothing

### ISSUE THREAD

**Issue by styfle** [frenic/csstype#54]
I used to be able to use `WebkitFontSmoothing: 'antialiased'` before `react.d.ts` moved to using `csstype`.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24688

Now that property is no longer available.

**Comment by rtsao** [comment]
Related: https://github.com/frenic/csstype/issues/39

**Comment by frenic** [comment]
You can always [fix this locally](https://github.com/frenic/csstype#what-should-i-do-when-i-get-type-errors). Closing.

**Comment by frenic** [comment]
You can open an issue at [MDN data](https://github.com/mdn/data) if you still want to go forward with this. But we won't patch it unless MDN decides it should be included.
