### ISSUE TITLE
Can't combine overflowX with !important

### ISSUE THREAD

**Issue by ppaul** [frenic/csstype#55]
I'm trying to override styles from a 3rd  party library, the only way being to use overflowX: scroll !important
However, type definitions doesn't allow that, although for simple overflow does allow (any) string.

**Comment by frenic** [comment]
The `overflow` shorthand property accepts space separated values. Therefore does it allow string (for now), but not the longhand properties.

It's quite rare that you have to use `!important` with style libraries so I don't find it motivated enough to allow string just for that reason. We actually aim for reducing the amount of `string` as much as possible to get stricter typing. So I would recommend you to use module augmentation or type assertion to solve this specific case. You have some examples here: https://github.com/frenic/csstype/blob/master/README.md#what-should-i-do-when-i-get-type-errors

**Comment by frenic** [comment]
Closing for now.
