### ISSUE TITLE
Split literal strings from base types

### ISSUE THREAD

**Issue by johanneslumpe** [frenic/csstype#57]
Properties like vertical-align allow literals but also the very wide `string` type. The issue with this is that TypeScript will widen the type to `string`, losing the ability to offer auto-completion hints for literal values and allowing _any_ string value to pass type-checking. Would it be possible to define types which allow a very wide type like this:

```ts
type VerticalAlignPropertyBase<TLength> = Globals | TLength | "baseline" | "bottom" | "middle" | "sub" | "super" | "text-bottom" | "text-top" | "top";
type VerticalAlignProperty<TLength> = VerticalAlignPropertyBase<TLength> | string;
```

**Auto-completion without split-out types**
<img width="724" alt="screen shot 2018-08-16 at 4 14 32 pm" src="https://user-images.githubusercontent.com/3470207/44232618-95b66300-a16f-11e8-9022-cd8ee3c03092.png">

**Auto-completion with split-out types**
<img width="926" alt="screen shot 2018-08-16 at 4 14 40 pm" src="https://user-images.githubusercontent.com/3470207/44232616-93540900-a16f-11e8-9f41-ecfe2321d07b.png">

It's possible that I'm missing an obvious way to remove `string` from the union and be left only with the literal types and `Globals`/`TLength`, but so far I've been unlucky with my attempts.

**Comment by johanneslumpe** [comment]
Just realized that this is basically the some solution proposed in https://github.com/frenic/csstype/issues/8#issuecomment-403489436

**Comment by frenic** [comment]
Closing if favor of #74
