### ISSUE TITLE
No autocompletition on property value

### ISSUE THREAD

**Issue by Eluminati** [frenic/csstype#60]
Hi there,

I found your awesome style definitions for typescript an I am emused to have this BUT the autocompletition does not work on values because they are always `string | undefined`.
The property "color" normaly should display valid color names but it doesn't.
I am using VS Code and at the moment there are no @types installed except typescript and its types Of course. It would be nice if you can fix this =)

Another thing is, that I need sometimes just a list of properties instead of an interface. For example PropertiesList = "background" | "backgroundPosition" | "color"  and so on. This would be a very nice feature.

**Comment by meyer** [comment]
@Eluminati for the first comment, see #8 and #57.

Regarding your second comment, you can use the following:
```js
import { Properties } from 'csstype';
type PropertiesList = keyof Properties;
```

**Comment by Eluminati** [comment]
Oh sorry, I forgot that this is possible. Thank you.
