### ISSUE TITLE
Should we remove the string type at the end of `DisplayProperty`?

### ISSUE THREAD

**Issue by vensa-albertgao** [frenic/csstype#64]
```typescript
export type DisplayProperty = Globals | DisplayOutside | DisplayInside | DisplayInternal | DisplayLegacy | "contents" | "list-item" | "none" | string;
```

The extra string in the end simply disable the feature of type checking, now the `display` could be anything like `foo` or `bar`.

Furthermore, in Typescript, you can't get intellisense, because it could be anything.
Should we remove it? Or I miss something?

Thanks :)

**Comment by pelotom** [comment]
See #8, #57, #60.

**Comment by vensa-albertgao** [comment]
Learned something! Thanks!
