### ISSUE TITLE
`width` and `height` should allow numbers

### ISSUE THREAD

**Issue by pelotom** [frenic/csstype#7]
Shouldn't these be of type `TLength`?

https://github.com/frenic/csstype/blob/e48d1c5c08896a8555829d76ba5ee9f022f7c964/index.d.ts#L325
https://github.com/frenic/csstype/blob/e48d1c5c08896a8555829d76ba5ee9f022f7c964/index.d.ts#L171

**Comment by frenic** [comment]
Wow, I've totally missed this. It should definitely contain `TLength`. By looking at the [spec](https://developer.mozilla.org/en-US/docs/Web/CSS/width#Formal_syntax), the component containing `<length>` is combined with another component using the `&&` combinator. Which means that both components are mandatory but may appear at any order. But the contaminated component also contains a tailing `?` which means that it's not mandatory. I guess this has confused the generator. Will look into this. Thanks!

**Comment by frenic** [comment]
Fixed in v1.6.0
