### ISSUE TITLE
How can I get only the type of properties strings?

### ISSUE THREAD

**Issue by imageslr** [frenic/csstype#70]
I want to check if a key is valid property key, such as 'font-size', 'font-family', which is `string` type. Is there some exported type in `csstype` can implement that? I tried to view source code but I'm a beginner of ts... If you could be so kind to give me some advices, I would be grateful!

**Comment by frenic** [comment]
You can use `keyof` to do this:

```ts
import { PropertiesHyphen, Properties } from 'csstype';
type HyphenatedNames = keyof PropertiesHyphen;
type CamelCasedNames = keyof Properties;
```

This till result in e.g. `"align-content" | "align-items" | "align-self" | "animation-delay" | "animation-direction" | "animation-duration" | "animation-fill-mode" | "animation-iteration-count" | ...`.

**Comment by imageslr** [comment]
Thank you very much! That solved my problem!!
