### ISSUE TITLE
Question: Why does some properties allow strings while other doesn't?

### ISSUE THREAD

**Issue by henninghall** [frenic/csstype#84]
Hi @frenic, I have a question! 😀

Most properties seem to allow string values even if they have a finite number of valid values, for instance:
```ts
type AlignItemsProperty = Globals | SelfPosition | "baseline" | "normal" | "stretch" | string;
type FlexFlowProperty = Globals | "column" | "column-reverse" | "nowrap" | "row" | "row-reverse" | "wrap" | "wrap-reverse" | string;
```

But other doesn't:
```ts
type FlexDirectionProperty = Globals | "column" | "column-reverse" | "row" | "row-reverse";
type FlexWrapProperty = Globals | "nowrap" | "wrap" | "wrap-reverse";
```

I ran into [these kinds of problems](https://github.com/microsoft/TypeScript/issues/11465) while using the properties that don't allow any string.

Is this intentional? 🤔

**Comment by meyer** [comment]
if you search closed issues for `string` you’ll see this question gets asked fairly frequently (it’s probably worth a README FAQ). There’s an explanation here: https://github.com/frenic/csstype/issues/8#issuecomment-364845647

**Comment by henninghall** [comment]
Thanks! So this is actually solved by https://github.com/frenic/csstype/pull/74? Is that also already released or does it come in v3?

**Comment by frenic** [comment]
The autocomplete issue is solved in `3.0.0@beta.1` by that PR. Not the type checking part.

**Comment by henninghall** [comment]
Alright! Do you already have an issue for the type checking part or do you want to keep this open for that?

**Comment by frenic** [comment]
We should close this. I don't believe there's much more we can do to improve type checking at this moment. We also have to keep in mind that false positive type errors are more annoying than false positive warnings in e.g. a linting tool. CSSType should only provide basic type checking and let the responsible to the developer and other tools where values becomes more complicated.
