### ISSUE TITLE
Installation of 3.0.0-beta fails if yarn is not installed

### ISSUE THREAD

**Issue by robeady** [frenic/csstype#89]
If I run 

```
npm install csstype@3.0.0-beta.2
```

then it fails with

```
> csstype@3.0.0-beta.2 install     
> yarn install --cwd __tests__

'yarn' is not recognized as an internal or external command,
operable program or batch file.
```

The cause appears to be https://github.com/frenic/csstype/commit/eaee5b952b6e7e2e11a53be95734525bd46e6b41#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R36

According to https://docs.npmjs.com/misc/scripts

> install, postinstall: Run AFTER the package is installed.

I'm guessing that this command should not be run when a user installs the package

**Comment by frenic** [comment]
Oups! My mistake. Fixed in `csstype@3.0.0-beta.3`
