### ISSUE TITLE
Mark logical inline/block margins+paddings as shorthands

### ISSUE THREAD

**Issue by kripod** [frenic/csstype#93]
Similarly to #92, the following properties are miscategorized as longhands:

- `margin-block`, `padding-block`
  - `margin-block-end`, `padding-block-end`
  - `margin-block-start`, `padding-block-start`
- `margin-inline`, `padding-inline`
  - `margin-inline-end`, `padding-inline-end`
  - `margin-inline-start`, `padding-inline-start`

**Comment by NotWoods** [comment]
Fixed in 7a4673d16e2205b9ecea77b5414ba5c9ecd0f660

**Comment by frenic** [comment]
Released in v3.1.2
