### ISSUE TITLE
Add `caret-shape` longhand and `caret` shorthand

### ISSUE THREAD

**Issue by kripod** [frenic/csstype#95]
Please see the [CSS Basic User Interface Module Level 4](https://www.w3.org/TR/css-ui-4/#insertion-caret) for further details. It also contains new properties like `nav-up`, `nav-right`, `nav-down` and `nav-left`.

**Comment by NotWoods** [comment]
Fixed in 7a4673d16e2205b9ecea77b5414ba5c9ecd0f660. `caret` and `caret-shape` were added.
